language: ruby
sudo: false
cache: bundler

rvm:
  - 2.5.3

script:
  - bundle exec ruby update-release-info.rb
  - bundle exec jekyll build
  - touch _site/.nojekyll

deploy:
  provider: pages
  skip-cleanup: true  # Keep HTML files generated during 'script'
  local-dir: _site
  github-token: $GITHUB_TOKEN
  target-branch: master
  keep-history: false  # Force update single commit on master branch
  on:
    branch: jekyll
