# Site settings
title: Yamcs
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.yamcs.org" # the base hostname & protocol for your site

exclude: [vendor]

markdown: kramdown

kramdown:
  input: GFM

highlighter: rouge
