title: Yamcs
url: "https://www.yamcs.org"

exclude:
  - vendor
  - "*.rb"
  - "*.sh"
  - README.md
  - Gemfile
  - Gemfile.lock

markdown: kramdown

kramdown:
  input: GFM

highlighter: rouge

proto: https://github.com/yamcs/yamcs/blob/master/yamcs-api/src/main/proto/yamcs/protobuf
